name: CI
on:
  - push

x-secret-envs: &secret-envs
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  REFRESH_SECRET: ${{ secrets.REFRESH_SECRET }}

x-aws-creds: &aws-creds
  uses: aws-actions/configure-aws-credentials@v1
  with:
    aws-access-key-id: "${{ secrets.AWS_ACCESS_KEY_ID }}"
    aws-secret-access-key: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
    aws-region: us-east-2

x-setup-node: &setup-node
  name: Setup node
  uses: actions/setup-node@v1
  with:
    node-version: '12.x'

x-setup-python: &setup-python
  name: Setup python
  uses: actions/setup-python@v1
  with:
    python-version: '3.8'

x-checkout-code: &checkout-code
  name: Checkout code
  uses: actions/checkout@v2

x-upload-node-modules: &upload-node-modules
  name: Upload node modules
  uses: actions/upload-artifact@v1
  with:
    name: Node Modules
    path: node_modules

x-download-node-modules: &download-node-modules
  name: Upload node modules
  uses: actions/download-artifact@v1
  with:
    name: Node Modules
    path: node_modules

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    env:
      <<: *secret-envs
    steps:
      - <<: *checkout-code
      - <<: *setup-python
      - run: pip install -Ur requirements.txt
      - run: make lint
  unit-test:
    runs-on: ubuntu-latest
    name: Unit test
    env:
      <<: *secret-envs
    steps:
      - <<: *checkout-code
      - <<: *setup-python
      - run: pip install -Ur requirements.txt
      - run: JWT_SECRET=${{ env.JWT_SECRET }} REFRESH_SECRET=${{ env.REFRESH_SECRET }} make unit-tests
  integration-test:
    runs-on: ubuntu-latest
    name: Integration test
    steps:
      - <<: *checkout-code
      - <<: *setup-node
      - <<: *setup-python
      - run: yarn
      - <<: *upload-node-modules
      - run: pip install -Ur requirements.txt
      - run: |
          JWT_SECRET=${{ secrets.JWT_SECRET }} \
          REFRESH_SECRET=${{ secrets.REFRESH_SECRET }} \
          TEST_VALID_BASIC_JWT=${{ secrets.TEST_VALID_BASIC_JWT }} \
          TEST_VALID_ADMIN_JWT=${{ secrets.TEST_VALID_ADMIN_JWT }} \
          TEST_INVALID_JWT=${{ secrets.TEST_INVALID_JWT }} \
          make integration-tests
  deploy-dev:
    needs:
      - lint
      - unit-test
      - integration-test
    runs-on: ubuntu-latest
    name: Deploy dev
    env:
      <<: *secret-envs
    if: github.ref == 'refs/heads/master'
    steps:
      - <<: *checkout-code
      - <<: *setup-node
      - <<: *setup-python
      - <<: *aws-creds
      - <<: *download-node-modules
      - run: pip install -Ur requirements.txt
      - run: JWT_SECRET=${{ env.JWT_SECRET }} REFRESH_SECRET=${{ env.REFRESH_SECRET }} make generate-secrets
      - run: yarn serverless deploy -s dev
  integration-test-remote:
    runs-on: ubuntu-latest
    needs:
      - deploy-dev
    name: Integration test remote
    steps:
      - <<: *checkout-code
      - <<: *setup-node
      - <<: *setup-python
      - <<: *aws-creds
      - <<: *download-node-modules
      - run: pip install -Ur requirements.txt
      - run: |
          JWT_SECRET=${{ secrets.JWT_SECRET }} \
          REFRESH_SECRET=${{ secrets.REFRESH_SECRET }} \
          TEST_VALID_BASIC_JWT=${{ secrets.TEST_VALID_BASIC_JWT }} \
          TEST_VALID_ADMIN_JWT=${{ secrets.TEST_VALID_ADMIN_JWT }} \
          TEST_INVALID_JWT=${{ secrets.TEST_INVALID_JWT }} \
          make integration-tests-remote
  deploy-prod:
    needs:
      - integration-test-remote
    runs-on: ubuntu-latest
    name: Deploy prod
    env:
      <<: *secret-envs
    if: github.ref == 'refs/heads/master'
    steps:
      - <<: *checkout-code
      - <<: *setup-node
      - <<: *setup-python
      - <<: *aws-creds
      - <<: *download-node-modules
      - run: pip install -Ur requirements.txt
      - run: JWT_SECRET=${{ env.JWT_SECRET }} REFRESH_SECRET=${{ env.REFRESH_SECRET }} make generate-secrets
      - run: yarn serverless deploy -s prod
  smoke-test:
    runs-on: ubuntu-latest
    needs:
      - deploy-prod
    name: Smoke test
    steps:
      - <<: *checkout-code
      - <<: *setup-node
      - <<: *setup-python
      - <<: *aws-creds
      - <<: *download-node-modules
      - run: pip install -Ur requirements.txt
      - run: |
          JWT_SECRET=${{ secrets.JWT_SECRET }} \
          REFRESH_SECRET=${{ secrets.REFRESH_SECRET }} \
          TEST_VALID_BASIC_JWT=${{ secrets.TEST_VALID_BASIC_JWT }} \
          TEST_VALID_ADMIN_JWT=${{ secrets.TEST_VALID_ADMIN_JWT }} \
          TEST_INVALID_JWT=${{ secrets.TEST_INVALID_JWT }} \
          make smoke-test
